apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - secrets.yaml

patches:
  - target:
      kind: SecretProviderClass
      name: grafana-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "f7a70032-03ea-43dc-8698-815c568798da"
      - op: replace
        path: /spec/parameters/tenantId
        value: "4183e53a-54a1-4dc5-bcb5-1a64a6fff3af"

configMapGenerator:
  - name: kube-prometheus-stack-values
    namespace: flux-system
    files:
      - values.yaml=values.yaml

configurations:
  - kustomizeconfig.yaml
