apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "f7a70032-03ea-43dc-8698-815c568798da"
      - op: replace
        path: /spec/parameters/tenantId
        value: "4183e53a-54a1-4dc5-bcb5-1a64a6fff3af"
  - target:
      kind: ObjectStore
      name: customer1-objectstore
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: "https://n8nbackupsstaginggee.blob.core.windows.net/customer1"
  - target:
      kind: Ingress
      name: customer1-ingress
    patch: |-
      - op: replace
        path: /spec/tls/0/hosts/0
        value: "customer1.n8n-staging.owoicho.org"
      - op: replace
        path: /spec/rules/0/host
        value: "customer1.n8n-staging.owoicho.org"
